import {money,totals,goalBalance,validate,validateState} from './finance.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const blank=()=>({transactions:[],goals:[],budget:0});let state=blank(),tab='home',filter='all',editing=null,mode='transaction';
try{const raw=localStorage.getItem('uangku-v1');if(raw)state=validateState(JSON.parse(raw))}catch{$('#notice').textContent='Data tersimpan tidak dapat dibaca. Pulihkan dari cadangan melalui Pengaturan.'}
$('#month').value=today().slice(0,7);
function persist(next){try{localStorage.setItem('uangku-v1',JSON.stringify(next));state=next;return true}catch{$('#error').textContent='Penyimpanan gagal. Cadangkan data dan periksa ruang perangkat.';$('#notice').textContent='Perubahan belum tersimpan.';return false}}
const categories=['Makan & minum','Transportasi','Belanja','Tagihan','Hiburan','Kesehatan','Lainnya'];
const label={income:'Pemasukan',expense:'Pengeluaran',save:'Setor tabungan',withdraw:'Ambil tabungan'};
function rows(list){return list.length?list.map(t=>`<div class="row"><div class="row-title"><div class="icon">${t.type==='expense'?'↗':t.type==='income'?'↙':'◇'}</div><div><h3>${esc(t.note||(['save','withdraw'].includes(t.type)?state.goals.find(g=>g.id===t.goal)?.name:t.category)||label[t.type])}</h3><p>${esc(t.date)} · ${label[t.type]}</p></div></div><div style="text-align:right"><strong class="${['income','withdraw'].includes(t.type)?'positive':'negative'}">${['income','withdraw'].includes(t.type)?'+':'−'} ${money(t.amount)}</strong><br><button class="quiet" data-edit="${esc(t.id)}">Edit</button><button class="quiet" data-delete="${esc(t.id)}">Hapus</button></div></div>`).join(''):`<div class="empty"><div class="symbol">☷</div><h3>Mulai dari catatan pertama</h3><p>Pengeluaran kecil pun punya cerita. Catat lewat tombol +.</p></div>`}
function render(){const m=$('#month').value,t=totals(state,m),list=state.transactions.filter(x=>x.date.startsWith(m)).sort((a,b)=>b.date.localeCompare(a.date));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
if(tab==='home'){const grouped={};list.filter(x=>x.type==='expense').forEach(x=>grouped[x.category]=(grouped[x.category]||0)+x.amount);$('#view').innerHTML=`<div class="cards"><div class="card hero"><p>UANG HARIAN TERSEDIA</p><div class="amount">${money(t.balance)}</div><small>Saldo seluruh waktu · di luar tabungan</small></div><div class="card"><p>PENGELUARAN BULAN INI</p><div class="amount">${money(t.expense)}</div><small>Pemasukan ${money(t.income)}</small></div><div class="card"><p>TABUNGAN TERKUMPUL</p><div class="amount">${money(t.savings)}</div><small>${state.goals.length} target untuk masa depan</small></div></div><div class="columns"><div class="panel"><div class="section-head"><h2>Catatan terbaru</h2><button data-open="transactions">Lihat semua →</button></div>${rows(list.slice(0,5))}</div><div><div class="panel"><div class="section-head"><h2>Ruang untuk bulan ini</h2><button data-budget>Atur</button></div>${state.budget?`<div class="amount">${money(state.budget-t.expense)}</div><p>${t.expense>state.budget?'Melebihi anggaran':'Sisa anggaran'} · batas ${money(state.budget)}</p><progress max="${state.budget}" value="${Math.min(t.expense,state.budget)}"></progress>`:'<p>Pasang batas bulanan supaya pengeluaran lebih terarah.</p>'}</div><div class="panel" style="margin-top:18px"><h2>Ke mana uang pergi?</h2>${Object.entries(grouped).sort((a,b)=>b[1]-a[1]).map(([c,n])=>`<div class="bar-row"><div><span>${esc(c)}</span><strong>${money(n)}</strong></div><progress max="${t.expense}" value="${n}"></progress></div>`).join('')||'<p>Rincian kategori muncul setelah kamu mencatat pengeluaran.</p>'}</div></div></div>`}
if(tab==='transactions')$('#view').innerHTML=`<div class="panel" style="margin-top:25px"><div class="section-head"><h2>Transaksi bulan ini</h2><button data-csv>Ekspor CSV</button></div><div class="filter">${['all',...Object.keys(label)].map(f=>`<button data-filter="${f}" class="${filter===f?'active':''}">${f==='all'?'Semua':label[f]}</button>`).join('')}</div>${rows(list.filter(x=>filter==='all'||x.type===filter))}</div>`;
if(tab==='savings')$('#view').innerHTML=`<div class="section-head" style="margin:28px 0"><div><h2>Rencana kecil, masa depan besar.</h2><p>Total terkumpul ${money(t.savings)}</p></div><button data-goal>＋ Target</button></div><div class="goal-grid">${state.goals.map(g=>{const b=goalBalance(state,g.id);return `<div class="panel"><div class="icon">◇</div><h2 style="margin-top:20px">${esc(g.name)}</h2><div class="amount">${money(b)}</div><p>dari ${money(g.target)} · ${Math.floor(b/g.target*100)}%</p><progress max="${g.target}" value="${Math.min(b,g.target)}"></progress><div class="goal-actions"><button data-save="${esc(g.id)}">＋ Setor</button><button data-withdraw="${esc(g.id)}">Ambil</button></div></div>`}).join('')||'<div class="panel empty"><div class="symbol">◇</div><h3>Apa yang ingin kamu wujudkan?</h3><p>Buat target pertama: dana darurat, liburan, atau sesuatu yang kamu impikan.</p><button data-goal>＋ Buat target tabungan</button></div>'}</div>`;
}
function field(name,text,type='text',value='',extra=''){return `<label>${text}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function open(kind='transaction',t={}){mode=kind;editing=t.id||null;$('#error').textContent='';$('#dialog-title').textContent=kind==='goal'?'Target tabungan baru':kind==='budget'?'Anggaran bulanan':kind==='settings'?'Pengaturan & cadangan':editing?'Edit transaksi':'Catat transaksi';$('#form .primary').hidden=kind==='settings';
$('#fields').innerHTML=kind==='goal'?field('name','Nama target','text','','required maxlength="80"')+field('target','Target nominal (Rp)','number','','required min="1" step="1"'):kind==='budget'?field('budget','Batas pengeluaran per bulan (Rp)','number',state.budget,'required min="0" step="1"')+'<p>Batas berlaku untuk semua bulan. Isi 0 untuk menonaktifkan.</p>':kind==='settings'?'<p>Data tersimpan di browser/perangkat ini. Belum ada login atau sinkronisasi antar perangkat.</p><p>Di Safari iPhone: Bagikan → Tambahkan ke Layar Utama.</p><div class="settings-actions"><button type="button" data-backup>Unduh cadangan JSON</button><label>Pulihkan cadangan<input type="file" id="restore" accept="application/json,.json"></label></div>':`<label>Jenis<select name="type">${Object.entries(label).map(([k,v])=>`<option value="${k}" ${k===(t.type||'expense')?'selected':''}>${v}</option>`).join('')}</select></label>`+field('amount','Nominal (Rp)','number',t.amount||'','required min="1" step="1" inputmode="numeric"')+field('date','Tanggal','date',t.date||today(),'required')+`<label id="cat-field">Kategori<select name="category">${categories.map(c=>`<option ${c===t.category?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label id="goal-field">Target tabungan<select name="goal"><option value="">Pilih target</option>${state.goals.map(g=>`<option value="${esc(g.id)}" ${g.id===t.goal?'selected':''}>${esc(g.name)}</option>`).join('')}</select></label>`+field('note','Catatan (opsional)','text',t.note||'','maxlength="160"');
if(kind==='transaction'){const update=()=>{const transfer=['save','withdraw'].includes($('#fields select[name=type]').value);$('#cat-field').hidden=transfer;$('#goal-field').hidden=!transfer};$('#fields select[name=type]').onchange=update;update()}if(!$('#dialog').open)$('#dialog').showModal();}
$('#form').onsubmit=e=>{e.preventDefault();try{const f=new FormData(e.target),next=structuredClone(state);if(mode==='goal')next.goals.push({id:crypto.randomUUID(),name:String(f.get('name')).trim(),target:Number(f.get('target'))});else if(mode==='budget')next.budget=Number(f.get('budget'));else{const t={id:editing||crypto.randomUUID(),type:f.get('type'),amount:Number(f.get('amount')),date:f.get('date'),category:f.get('category'),goal:f.get('goal'),note:String(f.get('note')).trim()};const base={...next,transactions:next.transactions.filter(x=>x.id!==editing)};validate(base,t);next.transactions=base.transactions.concat(t)}validateState(next);if(persist(next)){$('#dialog').close();render();$('#notice').textContent='Tersimpan.'}}catch(err){$('#error').textContent=err.message}};
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.tab){tab=d.tab;render()}if(d.open){tab=d.open;render()}if(d.filter){filter=d.filter;render()}if('goal'in d)open('goal');if('budget'in d)open('budget');if(d.save)open('transaction',{type:'save',goal:d.save});if(d.withdraw)open('transaction',{type:'withdraw',goal:d.withdraw});if(d.edit)open('transaction',state.transactions.find(t=>t.id===d.edit));if(d.delete&&confirm('Hapus transaksi ini?')){try{const next={...state,transactions:state.transactions.filter(t=>t.id!==d.delete)};validateState(next);if(persist(next))render()}catch(err){$('#notice').textContent='Tidak dapat menghapus: '+err.message}}if('backup'in d)download(JSON.stringify(state,null,2),`uangku-${today()}.json`,'application/json');if('csv'in d){const cell=v=>'"'+String(v).replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"';download('\uFEFF'+[['Tanggal','Jenis','Kategori','Nominal','Catatan'],...state.transactions.filter(t=>t.date.startsWith($('#month').value)).map(t=>[t.date,label[t.type],t.category,t.amount,t.note])].map(r=>r.map(cell).join(',')).join('\r\n'),`uangku-${$('#month').value}.csv`,'text/csv')}});
document.addEventListener('change',async e=>{if(e.target.id!=='restore'||!e.target.files[0])return;try{const data=validateState(JSON.parse(await e.target.files[0].text()));if(confirm('Ganti seluruh data perangkat ini dengan cadangan?')&&persist(data)){$('#dialog').close();render();$('#notice').textContent='Cadangan dipulihkan.'}}catch(err){$('#error').textContent=err.message}});
$('#add').onclick=()=>open();$('#settings').onclick=()=>open('settings');$('#close').onclick=()=>$('#dialog').close();$('#month').onchange=render;render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
