import {money,totals,goalBalance,validate,validateState,saveGoal,removeGoal} from './finance.js';
import {denku,goalReached} from './denku.js';
import {createMotionFeedback,savingsProgress} from './motion.js';
import {exportExcel,exportCsv} from './exports.js';
import {encodeBackup,decodeBackup} from './backup.js';
import {DriveBackup} from './cloud-backup.js?v=20260918-drive3';
import {createBackupFeedback} from './backup-feedback.js?v=20260919-targetfix2';
import {GOOGLE_CLIENT_ID} from './cloud-config.js?v=20260918-drive2';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const blank=()=>({transactions:[],goals:[],budget:0});let state=blank(),tab='home',filter='all',editing=null,mode='transaction';
try{const raw=localStorage.getItem('uangku-v1');if(raw)state=validateState(JSON.parse(raw))}catch{$('#notice').textContent='Data tersimpan tidak dapat dibaca. Pulihkan dari cadangan melalui Pengaturan.'}
$('#month').value=today().slice(0,7);
function persist(next){try{localStorage.setItem('uangku-v1',JSON.stringify(next));state=next;cloud.schedule();return true}catch{$('#error').textContent='Penyimpanan gagal. Cadangkan data dan periksa ruang perangkat.';$('#notice').textContent='Perubahan belum tersimpan.';return false}}
const cloud=new DriveBackup({clientId:GOOGLE_CLIENT_ID,getState:()=>state,onStatus:updateCloud});
const backupFeedback=createBackupFeedback();
const motion=createMotionFeedback();
function cloudMarkup(){const s=cloud.state;return `<h3>Backup Google Drive</h3><p role="status">${esc(s.message)}</p>${s.configured?`<div class="backup-buttons"><button type="button" data-connect ${!s.ready||s.busy?'disabled':''}>${s.connected?'Sambungkan ulang':'Sambungkan Google Drive'}</button><button type="button" data-cloud-backup ${!s.connected||s.busy?'disabled':''}>${s.busy?'Mencadangkan…':'Backup sekarang'}</button>${s.connected?'<button type="button" data-disconnect>Hentikan koneksi</button>':''}</div><p>Backup baru disimpan di My Drive → Uangku Backups: JSON seluruh data untuk pemulihan dan Excel bulan berjalan untuk laporan.</p>${s.folderUrl?`<a href="${esc(s.folderUrl)}" target="_blank" rel="noopener">Buka folder Uangku Backups ↗</a>`:''}<p>Otomatis saat aplikasi terbuka, online, dan sesi Google aktif. Sambungkan ulang setelah aplikasi dimuat ulang atau sesi berakhir.</p>${s.files.length?`<label>Salinan JSON (20 terbaru)<select id="cloud-file">${s.files.map(f=>`<option value="${esc(f.id)}">${esc(new Date(f.createdTime).toLocaleString('id-ID'))} — ${esc(f.name)}</option>`).join('')}</select></label><button type="button" data-cloud-restore ${s.busy?'disabled':''}>Pulihkan salinan pilihan</button>`:'<p>Belum ada salinan yang ditampilkan. Hubungkan Drive untuk memuat daftar.</p>'}`:'<p>Fitur sudah disiapkan, tetapi belum terhubung ke akun Google. Backup file JSON tetap tersedia.</p><a href="https://github.com/alden779/Uangku/blob/main/docs/backup-drive.md" target="_blank" rel="noopener">Panduan aktivasi Drive</a>'}<p>Salinan lama di area data aplikasi tetap dapat dipulihkan. Salinan antar perangkat tidak digabung otomatis.</p>`}
function updateCloud(s){const selected=$('#cloud-file')?.value;if($('#cloud-panel')){$('#cloud-panel').innerHTML=cloudMarkup();if(selected&&s.files.some(f=>f.id===selected))$('#cloud-file').value=selected}if($('#cloud-status'))$('#cloud-status').textContent=s.configured?s.message:'';backupFeedback.progress(s.message)}
const categories=['Makan & minum','Transportasi','Belanja','Tagihan','Hiburan','Kesehatan','Lainnya'];
const label={income:'Pemasukan',expense:'Pengeluaran',save:'Setor tabungan',withdraw:'Ambil tabungan'};
function rows(list){return list.length?list.map(t=>`<div class="row"><div class="row-title">${denku(t.type==='expense'?'kaget':t.type==='income'?'jempol':'celengan','row-denku')}<div><h3>${esc(t.note||(['save','withdraw'].includes(t.type)?state.goals.find(g=>g.id===t.goal)?.name:t.category)||label[t.type])}</h3><p>${esc(t.date)} · ${label[t.type]}</p></div></div><div style="text-align:right"><strong class="${['income','withdraw'].includes(t.type)?'positive':'negative'}">${['income','withdraw'].includes(t.type)?'+':'−'} ${money(t.amount)}</strong><br><button class="quiet" data-edit="${esc(t.id)}">Edit</button><button class="quiet" data-delete="${esc(t.id)}">Hapus</button></div></div>`).join(''):`<div class="empty denku-empty">${denku('berpikir','empty-denku')}<span class="sticker-label">DENKU lagi mikir…</span><h3>Dompet masih misterius!</h3><p>Putri, ada cerita uang apa hari ini? Catat lewat tombol +.</p></div>`}
function render(){const m=$('#month').value,t=totals(state,m),list=state.transactions.filter(x=>x.date.startsWith(m)).sort((a,b)=>b.date.localeCompare(a.date));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
if(tab==='home'){const grouped={};list.filter(x=>x.type==='expense').forEach(x=>grouped[x.category]=(grouped[x.category]||0)+x.amount);$('#view').innerHTML=`<div class="cards"><div class="card hero"><span class="card-sticker">DENKU jaga dompetmu ♡</span><p>UANG HARIAN TERSEDIA</p><div class="amount">${money(t.balance)}</div><small>Saldo seluruh waktu · di luar tabungan</small></div><div class="card expense-card"><div class="card-mascot">${denku('kaget','card-denku')}<span>Uang jalan-jalan!</span></div><p>PENGELUARAN BULAN INI</p><div class="amount">${money(t.expense)}</div><small>Pemasukan ${money(t.income)}</small></div><div class="card savings-card"><div class="card-mascot">${denku('celengan','card-denku')}<span>Misi: celengan gendut.</span></div><p>TABUNGAN TERKUMPUL</p><div class="amount">${money(t.savings)}</div><small>${state.goals.length} target untuk masa depan</small></div></div><div class="columns"><div class="panel"><div class="section-head"><h2>Catatan terbaru</h2><button data-open="transactions">Lihat semua →</button></div>${rows(list.slice(0,5))}</div><div><div class="panel"><div class="section-head"><h2>Ruang untuk bulan ini</h2><button data-budget>Atur</button></div>${state.budget?`<div class="amount">${money(state.budget-t.expense)}</div><p>${t.expense>state.budget?'DENKU mengingatkan: melewati batas':t.expense>=state.budget*.8?'DENKU mengingatkan: mendekati batas':'Sisa anggaran'} · batas ${money(state.budget)}</p><progress max="${state.budget}" value="${Math.min(t.expense,state.budget)}"></progress>`:'<p>Pasang batas bulanan supaya pengeluaran lebih terarah.</p>'}</div><div class="panel" style="margin-top:18px"><h2>Ke mana uang pergi?</h2>${Object.entries(grouped).sort((a,b)=>b[1]-a[1]).map(([c,n])=>`<div class="bar-row"><div><span>${esc(c)}</span><strong>${money(n)}</strong></div><progress max="${t.expense}" value="${n}"></progress></div>`).join('')||'<p>Rincian kategori muncul setelah kamu mencatat pengeluaran.</p>'}</div></div></div>`}
if(tab==='transactions')$('#view').innerHTML=`<div class="panel" style="margin-top:25px"><div class="section-head"><h2>Transaksi bulan ini</h2><button data-export>Ekspor laporan</button></div><div class="filter">${['all',...Object.keys(label)].map(f=>`<button data-filter="${f}" class="${filter===f?'active':''}">${f==='all'?'Semua':label[f]}</button>`).join('')}</div>${rows(list.filter(x=>filter==='all'||x.type===filter))}</div>`;
if(tab==='savings')$('#view').innerHTML=`<div class="section-head" style="margin:28px 0"><div><h2>Putri nabung, DENKU dukung!</h2><p>Total terkumpul ${money(t.savings)} · pelan-pelan jadi kenyataan.</p></div><button data-goal>＋ Target</button></div><div class="goal-grid">${state.goals.map(g=>{const b=goalBalance(state,g.id);return `<div class="panel goal-card ${b>=g.target?'goal-complete':''}"><div class="goal-card-head"><div class="goal-mascot">${denku(b>=g.target?'merayakan':'celengan','goal-denku')}<span class="sticker-label">${b>=g.target?'Target tercapai! Yeay!':'DENKU tim nabung'}</span></div><div class="goal-manage"><button class="quiet" data-edit-goal="${esc(g.id)}" aria-label="Edit target ${esc(g.name)}">Edit</button><button class="quiet danger" data-delete-goal="${esc(g.id)}" aria-label="Hapus target ${esc(g.name)}">Hapus</button></div></div><h2 style="margin-top:20px">${esc(g.name)}</h2><div class="amount">${money(b)}</div><p>dari ${money(g.target)} · ${Math.floor(b/g.target*100)}%</p><progress max="${g.target}" value="${Math.min(b,g.target)}"></progress><div class="goal-actions"><button data-save="${esc(g.id)}">＋ Setor</button><button data-withdraw="${esc(g.id)}">Ambil</button></div></div>`}).join('') ||`<div class="panel empty denku-empty">${denku('celengan','empty-denku')}<span class="sticker-label">Celengan DENKU siap!</span><h3>Putri mau nabung buat apa?</h3><p>Dana darurat, liburan, atau impianmu berikutnya. Yuk, buat target pertama.</p><button data-goal>＋ Buat target tabungan</button></div>`}</div>`;
}
function field(name,text,type='text',value='',extra=''){return `<label>${text}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function open(kind='transaction',t={}){
  mode=kind;editing=t.id||null;$('#error').textContent='';
  $('#dialog-title').textContent=kind==='goal'?(editing?'Edit target tabungan':'Target tabungan baru'):kind==='budget'?'Anggaran bulanan':kind==='settings'?'Pengaturan & backup':kind==='export'?'Ekspor laporan':editing?'Edit transaksi':'Catat transaksi';
  $('#form .primary').hidden=['settings','export'].includes(kind);
  if(kind==='goal')$('#fields').innerHTML=field('name','Nama target','text',t.name||'','required maxlength="80"')+field('target','Target nominal (Rp)','number',t.target||'','required min="1" step="1" inputmode="numeric"');
  else if(kind==='budget')$('#fields').innerHTML=field('budget','Batas pengeluaran per bulan (Rp)','number',state.budget,'required min="0" step="1"')+'<p>Batas berlaku untuk semua bulan. Isi 0 untuk menonaktifkan.</p>';
  else if(kind==='export')$('#fields').innerHTML=`<p>Laporan bulan ${esc($('#month').value)} mencakup semua jenis transaksi, termasuk yang disembunyikan oleh filter.</p><div class="export-options"><button type="button" data-excel><strong>Laporan Excel (.xlsx)</strong><span>Ringkasan bulan, transaksi, dan progres tabungan. Tabel rapi dengan format rupiah.</span></button><button type="button" data-csv><strong>Data transaksi CSV</strong><span>Untuk diimpor ke aplikasi lain. Bukan backup lengkap.</span></button></div><p>Untuk pindah perangkat, gunakan backup JSON di Pengaturan.</p>`;
  else if(kind==='settings'){
    $('#fields').innerHTML='<p>Data utama tersimpan di perangkat ini.</p><div class="backup-section"><h3>Backup file lengkap</h3><p>Semua transaksi, target tabungan, dan anggaran. Simpan file ke iCloud Drive atau pindahkan ke perangkat lain.</p><div class="settings-actions"><button type="button" data-backup>Unduh backup JSON</button><label>Pulihkan backup JSON<input type="file" id="restore" accept="application/json,.json"></label></div><p>Pemulihan mengganti seluruh data perangkat setelah konfirmasi. File backup versi awal tetap didukung.</p></div><div id="cloud-panel" class="backup-section"></div><p>Di Safari iPhone: Bagikan → Tambahkan ke Layar Utama.</p>';
    $('#cloud-panel').innerHTML=cloudMarkup();cloud.prepare();
  }else $('#fields').innerHTML=`<label>Jenis<select name="type">${Object.entries(label).map(([k,v])=>`<option value="${k}" ${k===(t.type||'expense')?'selected':''}>${v}</option>`).join('')}</select></label>`+field('amount','Nominal (Rp)','number',t.amount||'','required min="1" step="1" inputmode="numeric"')+field('date','Tanggal','date',t.date||today(),'required')+`<label id="cat-field">Kategori<select name="category">${categories.map(c=>`<option ${c===t.category?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label id="goal-field">Target tabungan<select name="goal"><option value="">Pilih target</option>${state.goals.map(g=>`<option value="${esc(g.id)}" ${g.id===t.goal?'selected':''}>${esc(g.name)}</option>`).join('')}</select></label>`+field('note','Catatan (opsional)','text',t.note||'','maxlength="160"');
  if(kind==='transaction'){const update=()=>{const transfer=['save','withdraw'].includes($('#fields select[name=type]').value);$('#cat-field').hidden=transfer;$('#goal-field').hidden=!transfer};$('#fields select[name=type]').onchange=update;update()}
  if(!$('#dialog').open)$('#dialog').showModal();
}
$('#form').onsubmit=e=>{e.preventDefault();if(['settings','export'].includes(mode))return;try{const f=new FormData(e.target);let next=structuredClone(state);if(mode==='goal')next=saveGoal(next,{id:editing||crypto.randomUUID(),name:f.get('name'),target:Number(f.get('target'))});else if(mode==='budget')next.budget=Number(f.get('budget'));else{const transfer=['save','withdraw'].includes(f.get('type'));const t={id:editing||crypto.randomUUID(),type:f.get('type'),amount:Number(f.get('amount')),date:f.get('date'),category:transfer?'Tabungan':f.get('category'),goal:transfer?f.get('goal'):'',note:String(f.get('note')).trim()};const base={...next,transactions:next.transactions.filter(x=>x.id!==editing)};validate(base,t);next.transactions=base.transactions.concat(t)}validateState(next);const celebrate=goalReached(state,next);if(persist(next)){$('#dialog').close();render();$('#notice').innerHTML=denku('jempol','notice-denku')+`<span>${mode==='goal'?(editing?'Target berhasil diperbarui.':'Target baru siap!'):'Tercatat! DENKU kasih jempol.'}</span>`;if(celebrate){backupFeedback.celebrate('Putri, target tabunganmu tercapai! DENKU ikut merayakan. Terus rawat impianmu berikutnya ♡')}else if(mode==='transaction'&&!editing){const kind=f.get('type');if(['save','withdraw','income','expense'].includes(kind))motion.play(kind,savingsProgress(state,f.get('goal')))}}}catch(err){$('#error').textContent=err.message}};
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.addEventListener('click',async e=>{
  const b=e.target.closest('button');if(!b)return;const d=b.dataset;
  if(d.tab){tab=d.tab;render()}if(d.open){tab=d.open;render()}if(d.filter){filter=d.filter;render()}
  if('goal'in d)open('goal');if(d.editGoal)open('goal',state.goals.find(g=>g.id===d.editGoal));if('budget'in d)open('budget');if('export'in d)open('export');
  if(d.save)open('transaction',{type:'save',goal:d.save});if(d.withdraw)open('transaction',{type:'withdraw',goal:d.withdraw});if(d.edit)open('transaction',state.transactions.find(t=>t.id===d.edit));
  try{
    if(d.delete&&confirm('Hapus transaksi ini?')){const next={...state,transactions:state.transactions.filter(t=>t.id!==d.delete)};validateState(next);if(persist(next))render()}
    if(d.deleteGoal){const goal=state.goals.find(g=>g.id===d.deleteGoal),count=state.transactions.filter(t=>t.goal===d.deleteGoal).length;if(goal&&confirm(`Hapus target “${goal.name}”?${count?` ${count} transaksi setor/ambil pada target ini juga akan dihapus.`:''}`)){if(persist(removeGoal(state,d.deleteGoal))){render();$('#notice').textContent='Target tabungan berhasil dihapus.'}}}
    if('backup'in d){download(encodeBackup(state),`uangku-backup-${today()}.json`,'application/json');$('#notice').textContent='Unduhan backup lengkap dimulai.'}
    if('csv'in d){download(exportCsv(state,$('#month').value),`uangku-data-${$('#month').value}.csv`,'text/csv');$('#notice').textContent='Unduhan CSV dimulai.'}
    if('excel'in d){download(exportExcel(state,$('#month').value),`uangku-laporan-${$('#month').value}.xlsx`,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');$('#notice').textContent='Unduhan laporan Excel dimulai.'}
    if('connect'in d)cloud.connect();if('disconnect'in d)cloud.disconnect();
    if('cloudBackup'in d){backupFeedback.show('loading','Menyiapkan backup JSON lengkap dan laporan Excel bulan berjalan…');try{const result=await cloud.flush(true);if(result?.file&&result?.report){motion.play('backup');backupFeedback.show('success','Backup JSON lengkap dan laporan Excel bulan '+result.month+' sudah tersimpan di folder Uangku Backups.',result.folderUrl)}else backupFeedback.show('error','Backup belum selesai. Periksa status koneksi Drive lalu coba lagi.')}catch(err){backupFeedback.show('error',err.message,cloud.state.folderUrl);throw err}}
    if('cloudRestore'in d){const original=state,id=$('#cloud-file').value,data=await cloud.restore(id);if(state!==original)throw Error('Data berubah selama mengambil backup. Pilih dan pulihkan ulang.');if(confirm('Ganti seluruh data perangkat dengan salinan Drive ini? Simpan backup JSON lokal terlebih dahulu jika diperlukan.')&&persist(data)){$('#dialog').close();render();$('#notice').textContent='Backup Drive dipulihkan.'}}
  }catch(err){$('#error').textContent=err.message;$('#notice').textContent=err.message}
});
document.addEventListener('change',async e=>{if(e.target.id!=='restore'||!e.target.files[0])return;try{const original=state,file=e.target.files[0];if(file.size>20*1024*1024)throw Error('Ukuran backup maksimal 20 MB.');const data=decodeBackup(await file.text());if(state!==original)throw Error('Data berubah selama membaca backup. Pilih file lagi.');if(confirm('Ganti seluruh data perangkat ini dengan backup?')&&persist(data)){$('#dialog').close();render();$('#notice').textContent='Backup dipulihkan.'}}catch(err){$('#error').textContent=err.message}finally{e.target.value=''}});
window.addEventListener('online',()=>{if(cloud.token)cloud.flush().catch(()=>{})});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&cloud.token)cloud.flush().catch(()=>{})});
$('#add').onclick=()=>open();$('#settings').onclick=()=>open('settings');$('#close').onclick=()=>$('#dialog').close();$('#month').onchange=render;render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
