import {test} from 'node:test';import assert from 'node:assert/strict';import {DriveBackup} from '../cloud-backup.js';import {encodeBackup} from '../backup.js';
const empty=()=>({budget:0,goals:[],transactions:[]});
const setup=(fetchFn)=>{let state=empty();const statuses=[];const c=new DriveBackup({clientId:'public-client',getState:()=>state,onStatus:s=>statuses.push(s),fetchFn,now:()=>100000,delay:100000});c.token='memory-only';c.expires=200000;return {c,statuses,setState:s=>{state=s}}};
test('Backup uploads immutable snapshots to appDataFolder and skips duplicate data',async()=>{const calls=[];const {c}=setup(async(url,o)=>{calls.push({url,...o});return new Response(JSON.stringify({id:'file-1',createdTime:'2026-09-18T00:00:00Z',name:'snapshot.json'}))});await c.flush(true);assert.equal(calls.length,1);assert.equal(calls[0].method,'POST');assert.match(calls[0].body,/"parents":\["appDataFolder"\]/);assert.match(calls[0].body,/"schemaVersion": 1/);assert.doesNotMatch(calls[0].body,/memory-only/);assert.equal(c.state.lastBackup,'1970-01-01T00:01:40.000Z');await c.flush(true);assert.equal(calls.length,1);c.disconnect()});
test('Expired sessions do not issue network requests or claim success',async()=>{const {c}=setup(()=>{throw Error('Should not fetch')});c.expires=99999;await assert.rejects(()=>c.flush(true),/Sesi Google berakhir/);assert.equal(c.state.connected,false);assert.equal(c.state.lastBackup,null);assert.ok(c.pending);c.disconnect()});
test('Offline failures retain pending data for retry',async()=>{let offline=true,calls=0;const {c}=setup(async()=>{calls++;if(offline)throw new TypeError('network');return new Response('{"id":"backup"}')});await assert.rejects(()=>c.flush(true),/tidak dapat dijangkau/);assert.equal(c.state.lastBackup,null);assert.ok(c.pending);offline=false;await c.flush();assert.equal(calls,2);assert.equal(c.pending,null);c.disconnect()});
test('Changes during an upload are not lost; disconnect does not claim success',async()=>{let finish;const {c,setState}=setup(()=>new Promise(r=>{finish=r}));const uploading=c.flush(true);setState({budget:100,goals:[],transactions:[]});c.schedule();finish(new Response('{"id":"first"}'));await uploading;assert.equal(c.pending.budget,100);c.disconnect();assert.equal(c.pending,null);assert.equal(c.state.connected,false)});
test('Restoration validates listed file IDs and contents',async()=>{const {c}=setup(async()=>new Response(encodeBackup(empty())));c.files=[{id:'valid-id'}];assert.deepEqual(await c.restore('valid-id'),empty());await assert.rejects(()=>c.restore('not-listed'),/Pilih cadangan/);c.disconnect()});
test('Disconnect cancels an in-flight request and keeps controls usable',async()=>{const {c}=setup((url,options)=>new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError')))));const uploading=c.flush(true);c.disconnect();await assert.rejects(()=>uploading);assert.equal(c.state.busy,false);assert.equal(c.state.connected,false);assert.equal(c.state.lastBackup,null);assert.match(c.state.message,/dihentikan/);assert.equal(c.controllers.size,0)});
