import {test} from 'node:test';
import assert from 'node:assert/strict';
import {exportExcel,exportCsv,reportData,transactionFields} from '../exports.js';
import {encodeBackup,decodeBackup} from '../backup.js';
const tx=(id,type,amount,date='2026-09-16',goal='',note='')=>({id,type,amount,date,goal,note,category:'Makan & minum'});
const sample={budget:2000000,goals:[{id:'g',name:'Dana darurat',target:10000000}],transactions:[tx('0','income',10000000,'2026-08-01'),tx('1','expense',100000),tx('2','save',3000000,'2026-09-16','g','Setor, pertama'),tx('3','withdraw',500000,'2026-09-18','g'),tx('4','expense',999999,'2026-10-01')]};
function unzip(bytes){const d=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),result={};let p=0;while(d.getUint32(p,true)===0x04034b50){assert.equal(d.getUint16(p+8,true),0);const size=d.getUint32(p+18,true),nameSize=d.getUint16(p+26,true),extra=d.getUint16(p+28,true),start=p+30+nameSize+extra;result[new TextDecoder().decode(bytes.slice(p+30,p+30+nameSize))]=new TextDecoder().decode(bytes.slice(start,start+size));p=start+size}assert.equal(d.getUint32(p,true),0x02014b50);return result}
test('Report uses month boundaries and excludes transfers from expenses',()=>{const d=reportData(sample,'2026-09');assert.equal(d.rows.length,3);assert.equal(d.opening,10000000);assert.equal(d.expense,100000);assert.equal(d.closing,7400000);assert.equal(d.savings,2500000);assert.equal(d.closing+d.savings,9900000);assert.equal(transactionFields(sample,sample.transactions[2])[2],'Tabungan');assert.equal(transactionFields(sample,sample.transactions[2])[3],'Dana darurat');assert.throws(()=>reportData(sample,'2026-13'))});
test('XLSX contains a real filtered table, numeric currency, typed dates and safe text',()=>{const s=structuredClone(sample);s.transactions[1].note='=HYPERLINK("https://example.org") & <test>';const files=unzip(exportExcel(s,'2026-09',new Date('2026-09-18T00:00:00Z')));assert.match(files['xl/workbook.xml'],/name="Ringkasan"/);assert.match(files['xl/worksheets/sheet2.xml'],/<pane ySplit="5"/);assert.match(files['xl/tables/table1.xml'],/ref="A5:F8"/);assert.match(files['xl/worksheets/sheet2.xml'],/<c r="E7" s="3"><v>3000000<\/v>/);assert.match(files['xl/worksheets/sheet2.xml'],/<c r="A6" s="4"><v>\d+<\/v>/);assert.match(files['xl/worksheets/sheet2.xml'],/&amp; &lt;test&gt;/);assert.doesNotMatch(files['xl/worksheets/sheet2.xml'],/<f>/);assert.match(files['xl/worksheets/sheet2.xml'],/Dana darurat/);assert.match(files['xl/styles.xml'],/numFmtId="164"/)});
test('Empty reports are valid without a fake transaction table',()=>{const files=unzip(exportExcel({budget:0,goals:[],transactions:[]},'2026-09'));assert.ok(files['xl/worksheets/sheet3.xml']);assert.equal(files['xl/tables/table1.xml'],undefined);assert.doesNotMatch(files['xl/worksheets/sheet2.xml'],/tableParts/)});
test('CSV uses Excel delimiter metadata, retains quoting, and neutralizes formula text',()=>{const s=structuredClone(sample);s.transactions[1].note=' =SUM(1;2)\n"test"';const csv=exportCsv(s,'2026-09');assert.ok(csv.startsWith('\uFEFFsep=;\r\n'));assert.match(csv,/"Target tabungan"/);assert.match(csv,/"Tabungan";"Dana darurat";"3000000"/);assert.match(csv,/"' =SUM\(1;2\)\n""test"""/)});
test('Versioned backup round trips all months and restores original legacy backups',()=>{assert.deepEqual(decodeBackup(encodeBackup(sample)),sample);assert.deepEqual(decodeBackup(JSON.stringify(sample)),sample);assert.equal(JSON.parse(encodeBackup(sample)).schemaVersion,1);assert.equal(decodeBackup(encodeBackup({...sample,token:'never-export'})).token,undefined);assert.throws(()=>decodeBackup('{"app":"uangku","schemaVersion":9}'));assert.throws(()=>decodeBackup('{}'));assert.throws(()=>decodeBackup('x'.repeat(20*1024*1024+1)))});

